version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.11.5
    resource_class: small
    steps:
      - checkout
      - run: python --version

#      - restore_cache:
#          keys:
#            - v2-dependencies-{{ checksum "pom.xml" }}
#            # fallback to using the latest cache if no exact match is found
#            - v2-dependencies-

      - run:
          name: Download Dependencies
          command: pip install -e .
      - run:
          name: Verify (Standard)
          command: pytest --junitxml=testresults.xml
      - store_test_results:
          path: testresults.xml
#      - save_cache:
#          paths:
#            - ~/.m2
#          key: v2-dependencies-{{ checksum "pom.xml" }}